name = "records-app"
main = "worker.js"
compatibility_date = "2026-01-01"

[[d1_databases]]
binding = "DB"
database_name = "chat_db"
database_id = "efefe0e5-9f85-4547-9237-9552889ea1c0"

# Ye lines HATADO - ye D1 ke andar nahi aani chahiye
# workers_dev = true
# preview_urls = true

# Inhe TOP level par rakho (if needed)
workers_dev = true
preview_urls = true